kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cluster-api-provider-juju-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath