apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: JujuConfiguration
metadata:
  name: juju-config-cluster-example
spec:
  controllerName: aws-eu-west-2
  modelName: charmedk8s
---
# Upon creation this will create a secret with the Kubeconfig for this cluster in
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: JujuCluster
metadata:
  name: cluster-example
spec:
  jujuConfiguration: juju-config-cluster-example
  overlay: |
    description: Charmed Kubernetes overlay to add Calico CNI.
    applications:
      calico:
        annotations:
          gui-x: '480'
          gui-y: '750'
        charm: cs:~containers/calico
      flannel:
    relations:
    - - calico:etcd
      - etcd:db
    - - calico:cni
      - kubernetes-master:cni
    - - calico:cni
      - kubernetes-worker:cni
